*&---------------------------------------------------------------------*
*& Include          ZMINESWEEPER_T01
*& Variable
*&---------------------------------------------------------------------*
REPORT ZMINESWEEPER MESSAGE-ID ZMINE.

TABLES: ZMINERANK.
DATA: GO_DOCKING_RANK TYPE REF TO CL_GUI_DOCKING_CONTAINER,
      GO_GRID_RANK    TYPE REF TO CL_GUI_ALV_GRID,
      GT_FCAT_RANK    TYPE TABLE OF LVC_S_FCAT,
      GS_LAYO         TYPE LVC_S_LAYO,
      GT_SORT         TYPE LVC_T_SORT,

      GS_COLOR        TYPE LVC_S_SCOL,
      GT_COLOR        TYPE LVC_T_SCOL.

DATA: BEGIN OF GS_RANKING,
        RANK     TYPE I,
        COLOR    TYPE LVC_T_SCOL,
        USERID   TYPE ZMINERANK-USERID,
        NAME     TYPE ZMINERANK-NAME,
        STEP     TYPE ZMINERANK-STEP,
        RANGE    TYPE ZMINERANK-RANGE,
        TIME     TYPE ZMINERANK-TIME,
        TOTAL    TYPE ZMINERANK-TOTAL,
        MINE_TOT TYPE ZMINERANK-MINE_TOT,

      END OF GS_RANKING,
      GT_RANKING LIKE TABLE OF GS_RANKING.



DATA: OK_CODE       TYPE SY-UCOMM,
      GV_SIZE       TYPE I,
      GV_STEP       TYPE I,
      RB_SAP        TYPE C LENGTH 1 VALUE 'X',
      RB_MARK       TYPE C LENGTH 1,
      GV_TOTAL_MINE TYPE I VALUE 0,
      GV_COUNT_MINE TYPE I VALUE 0.

DATA: GO_CONTAINER_PLAY TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_GRID_PLAY      TYPE REF TO CL_GUI_ALV_GRID,
      GT_FCAT_FIELD     TYPE LVC_T_FCAT.

CONSTANTS: GC_MINE TYPE ICON-ID VALUE '@39@',
           GC_FLAG TYPE ICON-ID VALUE '@DF@'.

FIELD-SYMBOLS: <FS_COL>  TYPE ANY,
               <FS_RANK> LIKE GS_RANKING.


"Mine Table
DATA: BEGIN OF GS_FIELD,
        INDEX TYPE N LENGTH 2,
        A0    TYPE C LENGTH 4,
        A1    TYPE C LENGTH 4,
        A2    TYPE C LENGTH 4,
        A3    TYPE C LENGTH 4,
        A4    TYPE C LENGTH 4,
        A5    TYPE C LENGTH 4,
        A6    TYPE C LENGTH 4,
        A7    TYPE C LENGTH 4,
        A8    TYPE C LENGTH 4,
        A9    TYPE C LENGTH 4,

        B0    TYPE C LENGTH 4,
        B1    TYPE C LENGTH 4,
        B2    TYPE C LENGTH 4,
        B3    TYPE C LENGTH 4,
        B4    TYPE C LENGTH 4,
        B5    TYPE C LENGTH 4,
        B6    TYPE C LENGTH 4,
        B7    TYPE C LENGTH 4,
        B8    TYPE C LENGTH 4,
        B9    TYPE C LENGTH 4,

        C0    TYPE C LENGTH 4,
        C1    TYPE C LENGTH 4,
        C2    TYPE C LENGTH 4,
        C3    TYPE C LENGTH 4,
        C4    TYPE C LENGTH 4,
        C5    TYPE C LENGTH 4,
        C6    TYPE C LENGTH 4,
        C7    TYPE C LENGTH 4,
        C8    TYPE C LENGTH 4,
        C9    TYPE C LENGTH 4,

        D0    TYPE C LENGTH 4,
        D1    TYPE C LENGTH 4,
        D2    TYPE C LENGTH 4,
        D3    TYPE C LENGTH 4,
        D4    TYPE C LENGTH 4,
        D5    TYPE C LENGTH 4,
        D6    TYPE C LENGTH 4,
        D7    TYPE C LENGTH 4,
        D8    TYPE C LENGTH 4,
        D9    TYPE C LENGTH 4,

      END OF GS_FIELD,
      GT_FIELD   LIKE TABLE OF GS_FIELD,

      GT_DISPLAY LIKE TABLE OF GS_FIELD.








*&---------------------------------------------------------------------*
*& Include          ZMINESWEEPER_T01
*& Selection - Screen
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B_03 WITH FRAME TITLE TEXT-003.
  PARAMETERS: P_NAME  LIKE GS_RANKING-NAME OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B_03.


SELECTION-SCREEN BEGIN OF BLOCK B_01 WITH FRAME TITLE TEXT-001.
  PARAMETERS: P_STEP1 TYPE C   RADIOBUTTON GROUP GR1 DEFAULT 'X',
              P_STEP2 TYPE C RADIOBUTTON GROUP GR1,
              P_STEP3 TYPE C RADIOBUTTON GROUP GR1.
SELECTION-SCREEN END OF BLOCK B_01.

SELECTION-SCREEN BEGIN OF BLOCK B_02 WITH FRAME TITLE TEXT-002.
  PARAMETERS: P_SIZE1 TYPE C   RADIOBUTTON GROUP GR2 DEFAULT 'X',
              P_SIZE2 TYPE C RADIOBUTTON GROUP GR2,
              P_SIZE3 TYPE C RADIOBUTTON GROUP GR2.
SELECTION-SCREEN END OF BLOCK B_02.

SELECTION-SCREEN BEGIN OF BLOCK B_04 WITH FRAME TITLE TEXT-004.
  SELECTION-SCREEN COMMENT 1(79) GV_TEXT1.
  SELECTION-SCREEN COMMENT /1(79) GV_TEXT2.
  SELECTION-SCREEN COMMENT /1(79) GV_TEXT3.
  SELECTION-SCREEN COMMENT /1(79) GV_TEXT4.
  SELECTION-SCREEN COMMENT /1(79) GV_TEXT5.
  SELECTION-SCREEN COMMENT /1(79) GV_TEXT6.
  SELECTION-SCREEN COMMENT /65(15) GV_TEXT7.

SELECTION-SCREEN END OF BLOCK B_04
.
